name: Hexo Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 每次推送到 main 分支时触发
      - mysource # 监听 mysource 分支的推送事件

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码仓库
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Hexo 推荐 Node.js 版本

      # 3. 安装依赖
      - name: Install Dependencies
        run: npm install

      # 4. 如果是 mysource 分支推送，合并并复制文件到 source 文件夹
      - name: Sync mysource to source folder (only on mysource push)
        if: github.ref == 'refs/heads/mysource'
        run: |
          # 创建一个新的临时目录，将 mysource 内容复制到 source 文件夹
          git fetch origin main
          git checkout main
          git pull origin main
          git checkout mysource -- .
          mkdir -p source
          cp -r * source/
          git add .
          git commit -m "Update source with mysource content"
          git push origin main

      # 5. 清理缓存文件（等同于 `hexo clean`）
      - name: Clean Cache
        run: npx hexo clean

      # 6. 生成静态文件（等同于 `hexo generate`）
      - name: Generate Static Files
        run: npx hexo generate

      # 7. 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GH_KEY }}
          publish_dir: ./public
          publish_branch: main # 指定部署到 main 分支
          external_repository: Natdog-6ix9ine/Natdog-6ix9ine.github.io
