name: Hexo Deploy to GitHub Pages

on:
  push:
    branches:
      - main        # 监听 main 分支的推送
      - mysource    # 监听 mysource 分支的推送

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码仓库
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. 安装依赖
      - name: Install Dependencies
        run: npm install

      # 4. 拉取所有远程分支，确保获取 `mysource` 分支
      - name: Fetch all branches
        run: |
          git fetch --all

      # 5. 将 mysource 内容复制到 source 文件夹
      - name: Sync mysource to source folder
        run: |
          # 获取 main 分支的最新代码
          git checkout main
          git pull origin main
          
          # 检查 mysource 分支是否存在
          git branch -r
          
          # 切换到 mysource 分支并拉取最新内容
          git checkout mysource || git checkout -b mysource origin/mysource

          # 合并 mysource 内容到 main 分支
          git checkout main
          git merge mysource --allow-unrelated-histories -m "Merge mysource into main"
          
          # 将内容放到 source 文件夹
          mkdir -p source
          cp -r * source/

      # 6. 清理缓存文件（等同于 `hexo clean`）
      - name: Clean Cache
        run: npx hexo clean

      # 7. 生成静态文件（等同于 `hexo generate`）
      - name: Generate Static Files
        run: npx hexo generate

      # 8. 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GH_KEY }}
          publish_dir: ./public
          publish_branch: main
          external_repository: Natdog-6ix9ine/Natdog-6ix9ine.github.io
